### PR TITLE
Splitting resources lecture into a component

### PR DESCRIPTION
**Pull request by Fausto95**
## Detailed purpose of the PR

This PR splits the resources preview into a component so we can re-use it anywhere

### Result and observation

- [ ] **Breaking changes ?**  
       If checked, what have you broken ?

- [ ] **Extra dependency ?**
      If checked, Which extra dependency did you add ? (name, purpose, link ...).

### Testing Strategy

- [x] Already covered by tests
- [ ] Manual testing
- [ ] Unit testing

### CODE REVIEW

**Comment by Fausto95** [comment]
I will need this in Context too

**Comment by Fausto95** [comment]
@chrisdugne 's version only consider rendering a video or a pdf and never both at the same time.
SO we'll merge this until he fixes it on what is currently working on!

**Comment by VincentCATILLON** [comment]
Closing it because it's outdated (seen with @chrisdugne )

**Comment by chrisdugne** [comment]
deprecated, see https://github.com/CoorpAcademy/mobile/pull/111

**Pull request closed without merging**
