### PR TITLE
Add haptic feedbacks on touchable things (buttons, area)

### PR DESCRIPTION
**Pull request by VincentCATILLON**
## Detailed purpose of the PR

This PR adds haptic feedbacks on every touchable area (`TouchableXXX` and `buttons`).

Btw, it moves the audio player module into HOC, like vibration does and add tests on it.

### Testing strategy

- [x] I ensured my code is tested: unit tests
- [x] I took care to mention breaking changes and extra libs if appropriate: `react-native-haptic-feedback`

### CODE REVIEW

**Comment by MelkMerle** [comment]
🚀 🎉

**Comment by VincentCATILLON** [comment]
@MelkMerle 👀

**Comment by VincentCATILLON** [comment]
Missing things:
- Duration on iOS/Android, maybe find to have something shorter
- Navigation header events
- Links on HTML events

**Comment by ThibaultRic** [comment]
If you want we can test it out with Sobia and give you feedback

**Comment by Fausto95** [comment]
Nice work, btw this PR introduces a little glitch at the Correction Screen UI in the swipable cards

**Pull request merged**
