### PR TITLE
Automatic version bumping

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
🚀  cc @marcmdm

### CODE REVIEW

**Comment by VincentCATILLON** [comment]
Don't we wan't only to create tags ? As it's supported at this time to detect version

**Comment by AdrieanKhisbe** [comment]
@VincentCATILLON J4ai rien compris

**Comment by AdrieanKhisbe** [comment]
@godu Oupsssiieeee 🌀

**Comment by AdrieanKhisbe** [comment]
rebasée :)

**Pull request merged**
