### PR TITLE
React.useContext(JustForFC)

### PR DESCRIPTION
**Pull request by Fausto95**
🎅 Hooo Hooo Hoo Hooooooks 🎅

### CODE REVIEW

**Comment by Fausto95** [comment]
I may want to add this: https://www.npmjs.com/package/eslint-plugin-react-hooks

**Comment by Volubyl** [comment]
👏 👏 👏 👏 👏 👏 👏 👏

**Comment by VincentCATILLON** [comment]
@Volubyl tell me its ok for him

**Pull request merged**
