### PR TITLE
Fixing env update when yarn start

### PR DESCRIPTION
**Pull request by alanlanglois**
## Detailed purpose of the PR

Fixing leve-end statusbar height not set properly when switching from storybook / e2e to normal build : https://trello.com/c/pPkH4FpL/1730-various-display-bugs

| BEFORE  | AFTER|
| ------------- | ------------- |
|  |   |

### Testing strategy

- [x] I ensured my code is tested: tested on emulators
- [ ] I took care to mention breaking changes and extra libs if appropriate

### CODE REVIEW

**Comment by alanlanglois** [comment]
[AA mobile user, i can't play the video in the popin if i have already watched the video](https://trello.com/c/3Lfk0LW2/1454-aa-mobile-user-i-cant-play-the-video-in-the-popin-if-i-have-already-watched-the-video)

**Comment by Fausto95** [comment]
This is not working for me :( . Gonna check why!

**Comment by alanlanglois** [comment]
> This is not working for me :( . Gonna check why!

Check: modules/version.json, it should rewrites the file and remove le flavorBuild 'storybook'

image

**Comment by Fausto95** [comment]
We can ship this

**Comment by alanlanglois** [comment]
[Various display bugs](https://trello.com/c/pPkH4FpL/1730-various-display-bugs)

**Pull request merged**
